lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
theme: jekyll-theme-midnight
markdown: kramdown
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false

